# Install Docker
- include_tasks: ../../tasks/docker.yaml

- name: Copy Dkr Compose file
  ansible.builtin.copy:
    src: "docker-install/docker-compose.yaml"
    dest: "{{ project_path }}/docker-compose.yaml"
    force: yes

- name: Copy Dkr file
  ansible.builtin.copy:
    src: "docker-install/Dockerfile"
    dest: "{{ project_path }}/Dockerfile"
    force: yes

- name: "Copy .env template"
  template:
    src: "docker-install/.env.j2"
    dest: "{{ project_path }}/.env"
    force: yes

- name: Create database
  command: "docker compose run --rm server create_db"
  args:
    chdir: "{{ project_path }}"

- name: Install redash
  command: docker compose up -d --force-recreate
  args:
    chdir: "{{ project_path }}"

- name: Pause play until a URL is reachable from this host
  ignore_errors: true
  ansible.builtin.uri:
    url: "http://127.0.0.1"
    follow_redirects: none
    validate_certs: no
    method: GET
  register: _result
  until: _result.status >= 200
  retries: 30
  delay: 5
