version: "9"
services:
  redis:
    image: redis:7.0.8-alpine
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis-data:/data

  server:
    build:
      context: .
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./infrastructure/terraform/variables.tfvars:/app/infrastructure/terraform/variables.tfvars
      - server-logs:/app/infrastructure/provisioner/logs
      - server-terraform:/app/infrastructure/terraform
    ports:
      - 8088:8088

volumes:
  redis-data:
  server-logs:
  server-terraform:
