---
- name: Install Dkr dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - uidmap
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
    - lsb-release

- name: Add Dkr GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Dkr repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Dkr | Install
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
    state: present
    update_cache: true

- name: Dkr | Install Dkr Module for Python
  pip:
    name: docker

- name: Dkr | Add group user
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
