# Variable output (puppeteer_folder)
- include_tasks: ../../tasks/puppeteer-localhost.yaml

- name: Puppeteer Files
  set_fact:
    wordpress_file: "{{ puppeteer_folder }}/src/{{ random_secret }}-wordpress-initial-setup.ts"

- name: "Copy wordpress-initial-setup.ts.j2 template"
  become: false
  template:
    src: puppeteer/wordpress-initial-setup.ts.j2
    dest: "{{ wordpress_file }}"
    force: yes

- name: "Run wordpress-initial-setup.ts"
  become: false
  command: "pnpm ts-node {{ wordpress_file }}"
  args:
    chdir: "{{ puppeteer_folder }}"
  ignore_errors: true

- name: "Remove {{ wordpress_file }}"
  become: false
  command: "rm -rf {{ wordpress_file }}"
  args:
    chdir: "{{ puppeteer_folder }}"
  ignore_errors: true
