---
- name: Redash
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # Wait until all unable to acquire the dpkg frontend lock process finished
    - include_tasks: ../../tasks/cloud-init.yaml

    # Playbook init (with decoded_metadata, project_path)
    - include_tasks: ../../tasks/playbook-init.yaml

    - name: Extract Required Variables
      set_fact:
        domain: "{{ decoded_metadata | json_query('domain') }}"
        admin_name: "{{ decoded_metadata | json_query('admin_name') }}"
        admin_email: "{{ decoded_metadata | json_query('admin_email') }}"
        organization_name: "{{ decoded_metadata | json_query('organization_name') }}"

    # Validate domain variable
    - include_tasks: ../../tasks/validator/domain-regex.yaml
      vars:
        domain_var: "{{ domain }}"

    - include_tasks: ../../tasks/validator/email-regex.yaml
      vars:
        email_var: "{{ admin_email }}"

    - name: Copy setup.sh
      ansible.builtin.copy:
        src: setup.sh
        dest: "{{ project_path }}/setup.sh"
        force: yes

    - name: Give the installer executable permissions
      shell: "chmod u+x setup.sh"
      args:
        chdir: "{{ project_path }}"

    - name: Install Redash
      shell: ./setup.sh
      args:
        chdir: "{{ project_path }}"
        executable: /bin/bash
        creates: /opt/redash

    - name: Pause play until a URL is reachable from this host
      ignore_errors: true
      ansible.builtin.uri:
        url: "http://127.0.0.1"
        follow_redirects: none
        validate_certs: no
        method: GET
      register: _result
      until: _result.status >= 200
      retries: 30
      delay: 5

    # Account setup
    - import_tasks: account-setup.yaml
      delegate_to: 127.0.0.1

    - include_tasks: ../../tasks/expose-variable.yaml
      vars:
        text: |
          Login
          Email: {{ admin_email }}
          Password: {{ app_secret }}

        credentials:
          email: "{{ admin_email }}"
          password: "{{ app_secret }}"
