# Install Python prerequisite
- name: Install Python prerequisite
  ansible.builtin.package:
    name:
      - python3-dev
      - python3.10-dev
      - python3-setuptools
      - python3-pip
      - python3-distutils
      - python3.10-venv
    state: present

# Install prerequisite
- name: Install Tools
  ansible.builtin.package:
    name:
      - curl
      - git
      - redis-server
      - software-properties-common
      - supervisor
      - nginx
    state: present

# Install prerequisite
- name: Install other necessary packages
  ansible.builtin.package:
    name:
      - xvfb
      - libfontconfig
      - wkhtmltopdf
    state: present

# Include task mysql.yaml
- include_tasks: ../../tasks/mysql.yaml
  tags: [mysql]

- name: Replace the content MariaDB My-Config
  copy:
    src: mysql-my.cnf
    dest: /etc/mysql/my.cnf
    force: yes

- name: Restart service MariaDB
  ansible.builtin.service:
    name: mysql
    state: restarted

# Include task mysql.yaml
- include_tasks: ../../tasks/nodejs.yaml
  tags: [nodejs]

##################################
# INSTALL FRAPPE BENCH
##################################

- name: Install Frappe Bench
  tags: [frappe]
  pip:
    name: frappe-bench
    state: present

- name: Frappe Bench Path
  tags: [frappe]
  set_fact:
    frappe_path: "{{ project_path }}/frappe-bench"

- name: Frappe | Initialize Frappe Bench
  tags: [frappe]
  become: false
  shell: "chmod -R o+rx /home/{{ ansible_user }}"
  args:
    chdir: "{{ project_path }}"

- name: Frappe | Initialize Frappe Bench
  tags: [frappe]
  become: false
  shell: "bench init --frappe-branch version-{{ frappe_version }} frappe-bench"
  args:
    chdir: "{{ project_path }}"
    creates: "{{ frappe_path }}"

# Setup production
- name: Frappe | Bench setup production
  tags: [frappe]
  become: true
  shell: "bench setup production {{ ansible_user }} --yes"
  args:
    executable: /bin/bash
    chdir: "{{ frappe_path }}"
  ignore_errors: true

# Create a New Site
- name: Frappe | Create new site
  tags: [frappe]
  become: false
  shell: "bench new-site {{ domain }} --db-root-password {{ mysql_root_password }} --admin-password {{ random_secret }}"
  args:
    chdir: "{{ frappe_path }}"
    creates: "{{ frappe_path }}/sites/{{ domain }}"
  ignore_errors: true
  register: create_site_result

# Setup production
- name: Frappe | Bench setup production
  tags: [frappe]
  become: true
  shell: "bench setup production {{ ansible_user }} --yes"
  args:
    executable: /bin/bash
    chdir: "{{ frappe_path }}"
  ignore_errors: true

- name: Frappe | Bench restart
  tags: [frappe]
  become: true
  shell: "bench restart"
  args:
    chdir: "{{ frappe_path }}"
  ignore_errors: true

- name: Frappe | Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

# Create a New Site
- name: Frappe | Create new site
  tags: [frappe]
  become: false
  shell: "bench new-site {{ domain }} --force --db-root-password {{ mysql_root_password }} --admin-password {{ random_secret }}"
  args:
    chdir: "{{ frappe_path }}"
  when: create_site_result.rc != 0

# DOWNLOAD APPS
- name: "Frappe Download App | {{ item.name }}"
  become: false
  shell: "bench get-app {{ item.source }}"
  args:
    chdir: "{{ frappe_path }}"
    creates: "{{ frappe_path }}/apps/{{ item.name }}"
  loop:
    - { name: "payments", source: "payments" }
    - {
        name: "erpnext",
        source: "--branch version-{{ frappe_version }} erpnext",
      }
    - { name: "hrms", source: "hrms" }
    - {
        name: "ecommerce_integrations",
        source: "ecommerce_integrations --branch main",
      }
    - { name: "chat", source: "chat" }
    - { name: "helpdesk", source: "helpdesk" }
    # - { name: "lending", source: "lending" }
    # - { name: "changemakers", source: "changemakers" }
    # - { name: "healthcare", source: "healthcare" }
    # - { name: "lms", source: "lms" }
    # - { name: "insights", source: "https://github.com/frappe/insights" }
    # - { name: "drive", source: "https://github.com/frappe/drive" }

# INSTALL APPS
- name: "Frappe Install App | {{ item }}"
  become: false
  shell: "bench --site {{ domain }} install-app {{ item }}"
  args:
    chdir: "{{ frappe_path }}"
  loop:
    - erpnext
    - hrms
    - ecommerce_integrations
    - chat
    - helpdesk
    # - lending
    # - changemakers
    # - healthcare
    # - lms
    # - insights
    # - drive

# SETUP PRODUCTION SERVER
- name: Frappe | Enable scheduler service.
  become: false
  shell: "bench --site {{ domain }} enable-scheduler"
  args:
    chdir: "{{ frappe_path }}"

# - name: Frappe | add-to-hosts.
#   become: false
#   shell: "bench --site {{ domain }} add-to-hosts"
#   args:
#     chdir: "{{ frappe_path }}"

- name: Frappe | Disable maintenance mode.
  become: false
  shell: "bench --site {{ domain }} set-maintenance-mode off"
  args:
    chdir: "{{ frappe_path }}"

- name: Frappe | Bench setup production reload
  tags: [frappe]
  become: true
  shell: "bench setup production {{ ansible_user }} --yes"
  args:
    chdir: "{{ frappe_path }}"
  ignore_errors: true
