# Install Python prerequisite
- name: Install Python prerequisite
  ansible.builtin.package:
    name:
      - python3-dev
      - python3.10-dev
      - python3-setuptools
      - python3-pip
      - python3-distutils
      - python3.10-venv
    state: present

# Install prerequisite
- name: Install Tools
  ansible.builtin.package:
    name:
      - curl
      - git
      - redis-server
      - software-properties-common
      - supervisor
      - nginx
    state: present

# Install prerequisite
- name: Install other necessary packages
  ansible.builtin.package:
    name:
      - xvfb
      - libfontconfig
      - wkhtmltopdf
    state: present

# Include task mysql.yaml
- include_tasks: ../../tasks/mysql.yaml
  tags: [mysql]

- name: Replace the content MariaDB My-Config
  copy:
    src: mysql-my.cnf
    dest: /etc/mysql/my.cnf
    force: yes

- name: Restart service MariaDB
  ansible.builtin.service:
    name: mysql
    state: restarted

# Include task mysql.yaml
- include_tasks: ../../tasks/nodejs.yaml
  tags: [nodejs]

##################################
# INSTALL FRAPPE BENCH
##################################

- name: Install Frappe Bench
  tags: [frappe]
  pip:
    name: frappe-bench
    state: present

- name: Frappe Bench Path
  tags: [frappe]
  set_fact:
    frappe_path: "{{ project_path }}/frappe-bench"

- name: Frappe | Initialize Frappe Bench
  tags: [frappe]
  become: false
  shell: "chmod -R o+rx /home/{{ ansible_user }}"
  args:
    chdir: "{{ project_path }}"

- name: Frappe | Initialize Frappe Bench
  tags: [frappe]
  become: false
  shell: "bench init --frappe-branch version-{{ frappe_version }} frappe-bench"
  args:
    chdir: "{{ project_path }}"
    creates: "{{ frappe_path }}"

# Setup production
- name: Frappe | Bench setup production
  tags: [frappe]
  become: true
  shell: "bench setup production {{ ansible_user }} --yes"
  args:
    executable: /bin/bash
    chdir: "{{ frappe_path }}"
  ignore_errors: true

# Create a New Site
- name: Frappe | Create new site
  tags: [frappe]
  become: false
  shell: "bench new-site {{ domain }} --db-root-password {{ mysql_root_password }} --admin-password {{ random_secret }}"
  args:
    chdir: "{{ frappe_path }}"
    creates: "{{ frappe_path }}/sites/{{ domain }}"
  ignore_errors: true
  register: create_site_result

# Setup production
- name: Frappe | Bench setup production
  tags: [frappe]
  become: true
  shell: "bench setup production {{ ansible_user }} --yes"
  args:
    executable: /bin/bash
    chdir: "{{ frappe_path }}"
  ignore_errors: true

- name: Frappe | Bench restart
  tags: [frappe]
  become: true
  shell: "bench restart"
  args:
    chdir: "{{ frappe_path }}"
  ignore_errors: true

- name: Frappe | Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

# Create a New Site
- name: Frappe | Create new site
  tags: [frappe]
  become: false
  shell: "bench new-site {{ domain }} --force --db-root-password {{ mysql_root_password }} --admin-password {{ random_secret }}"
  args:
    chdir: "{{ frappe_path }}"
  when: create_site_result.rc != 0

# DOWNLOAD APPS
- name: Frappe | Download the payments apps.
  become: false
  shell: "bench get-app payments"
  args:
    chdir: "{{ frappe_path }}"
    creates: "{{ frappe_path }}/apps/payments"

- name: Frappe | Download the main ERPNext app.
  become: false
  shell: "bench get-app --branch version-{{ frappe_version }} erpnext"
  args:
    chdir: "{{ frappe_path }}"
    creates: "{{ frappe_path }}/apps/erpnext"

- name: Frappe | Download the HR & Payroll app.
  become: false
  shell: "bench get-app hrms"
  args:
    chdir: "{{ frappe_path }}"
    creates: "{{ frappe_path }}/apps/hrms"

- name: Frappe | Download the ecommerce integrations apps.
  become: false
  shell: "bench get-app ecommerce_integrations --branch main"
  args:
    chdir: "{{ frappe_path }}"
    creates: "{{ frappe_path }}/apps/ecommerce_integrations"

# INSTALL APPS
- name: Frappe | Install the main ERPNext app.
  become: false
  shell: "bench --site {{ domain }} install-app erpnext"
  args:
    chdir: "{{ frappe_path }}"

- name: Frappe | Install the HR & Payroll app.
  become: false
  shell: "bench --site {{ domain }} install-app hrms"
  args:
    chdir: "{{ frappe_path }}"

- name: Frappe | Install the ecommerce integrations apps.
  become: false
  shell: "bench --site {{ domain }} install-app ecommerce_integrations"
  args:
    chdir: "{{ frappe_path }}"

# SETUP PRODUCTION SERVER
- name: Frappe | Enable scheduler service.
  become: false
  shell: "bench --site {{ domain }} enable-scheduler"
  args:
    chdir: "{{ frappe_path }}"

# - name: Frappe | add-to-hosts.
#   become: false
#   shell: "bench --site {{ domain }} add-to-hosts"
#   args:
#     chdir: "{{ frappe_path }}"

- name: Frappe | Disable maintenance mode.
  become: false
  shell: "bench --site {{ domain }} set-maintenance-mode off"
  args:
    chdir: "{{ frappe_path }}"

- name: Frappe | Bench setup production reload
  tags: [frappe]
  become: true
  shell: "bench setup production {{ ansible_user }} --yes"
  args:
    chdir: "{{ frappe_path }}"
  ignore_errors: true
