# Variable output (puppeteer_folder)
- include_tasks: ../../tasks/puppeteer-localhost.yaml

- name: Puppeteer Files
  set_fact:
    drupal_file: "{{ puppeteer_folder }}/src/{{ random_secret }}-drupal-initial-setup.ts"

- name: "Copy initial-setup.ts.j2 template"
  become: false
  template:
    src: puppeteer/initial-setup.ts.j2
    dest: "{{ drupal_file }}"
    force: yes

- name: "Run drupal-initial-setup.ts"
  become: false
  command: "pnpm ts-node {{ drupal_file }}"
  args:
    chdir: "{{ puppeteer_folder }}"

- name: "Remove {{ drupal_file }}"
  become: false
  command: "rm -rf {{ drupal_file }}"
  args:
    chdir: "{{ puppeteer_folder }}"
