---
- name: Dupral
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # Wait until all unable to acquire the dpkg frontend lock process finished
    - include_tasks: ../../tasks/cloud-init.yaml

    # Playbook init (with decoded_metadata, project_path, app_secret, admin_email)
    - include_tasks: ../../tasks/playbook-init.yaml

    - name: Extract Required Variables
      set_fact:
        domain: "{{ decoded_metadata | json_query('domain') }}"

    # Validate domain variable
    - include_tasks: ../../tasks/validator/domain-regex.yaml
      vars:
        domain_var: "{{ domain }}"

    - name: Deploy Dupral and dependencies
      include_role:
        name: "{{ roleinput }}"
      loop:
        - geerlingguy.apache
        - geerlingguy.mysql
        - geerlingguy.php-versions
        - geerlingguy.php
        - geerlingguy.php-mysql
        - geerlingguy.composer
        - geerlingguy.drush
        - geerlingguy.drupal
      loop_control:
        loop_var: roleinput
      vars:
        drupal_install_site: true
        drupal_build_composer_project: true
        drupal_composer_install_dir: "/var/www/drupal"
        drupal_core_path: "{{ drupal_composer_install_dir }}/web"
        drupal_domain: "{{ domain }}"
        drupal_account_name: admin
        drupal_account_pass: "{{ app_secret }}"

    - include_tasks: ../../tasks/expose-variable.yaml
      vars:
        text: |
          Login
          Email: admin
          Password: {{ app_secret }}
        credentials:
          username: "admin"
          password: "{{ app_secret }}"
