# Install Docker
- include_tasks: ../../tasks/docker.yaml

- name: Copy Docker file
  ansible.builtin.copy:
    src: "docker-compose.yaml"
    dest: "{{ project_path }}/docker-compose.yaml"
    force: yes

- name: "Copy .env template"
  template:
    src: .env.j2
    dest: "{{ project_path }}/.env"
    force: yes

- name: Install Mautic using Docker Compose
  become: true
  command: docker compose up -d
  args:
    chdir: "{{ project_path }}"

- name: Pause play until a URL is reachable from this host
  ignore_errors: true
  ansible.builtin.uri:
    url: "http://127.0.0.1:8880"
    follow_redirects: none
    validate_certs: no
    method: GET
  register: _result
  until: _result.status >= 200
  retries: 30
  delay: 5
