version: "3"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: unless-stopped
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    env_file:
      - .env

  mautic:
    container_name: mautic
    depends_on:
      - mariadb
    image: mautic/mautic:v4-apache
    volumes:
      - mautic_data:/var/www/html
    restart: unless-stopped
    ports:
      - "8880:80"
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
  mautic_data:
    driver: local
