# Install Docker
- include_tasks: ../../tasks/docker.yaml

- name: Copy Docker file
  ansible.builtin.copy:
    src: "docker-compose.yaml"
    dest: "{{ project_path }}/docker-compose.yaml"
    force: yes

- name: "Copy .env template"
  template:
    src: .env.j2
    dest: "{{ project_path }}/.env"
    force: yes

- name: Install Moodle using Docker Compose
  become: true
  command: docker compose up -d
  args:
    chdir: "{{ project_path }}"
