# Install Docker
- include_tasks: ../../tasks/docker.yaml

- name: Copy Docker file
  ansible.builtin.copy:
    src: "docker-compose.yaml"
    dest: "{{ project_path }}/docker-compose.yaml"
    force: yes

- name: Install Moodle using Docker Compose
  become: true
  command: docker compose up -d
  args:
    chdir: "{{ project_path }}"
  environment:
    MOODLE_USERNAME: "{{ moodle_username }}"
    MOODLE_EMAIL: "{{ moodle_email }}"
    MOODLE_SITE_NAME: "{{ moodle_site_name }}"
