---
- name: Moodle Configuration
  hosts: localhost
  become: false
  gather_facts: true
  vars:
    oidc_plugin_name: "auth_oidc_moodle42_2023042400.zip"
    oidc_plugin_url: "https://moodle.org/plugins/download.php/29296/{{ oidc_plugin_name }}"

  tasks:
    - name: Decode base64 platform_metadata variable
      set_fact:
        decoded_metadata: "{{ platform_metadata | b64decode }}"

    - name: Extract Required Variables
      set_fact:
        admin_username: "{{ decoded_metadata | json_query('admin_username') }}"
        admin_password: "{{ decoded_metadata | json_query('admin_password') }}"
        configuration: "{{ decoded_metadata | json_query('configuration') }}"

    # Validate domain variable
    - import_tasks: ../../tasks/validator/url-ws-regex.yaml
      vars:
        url_var: "{{ configuration['keycloak_url'] }}"

    - import_tasks: sso-configuration.yaml
