# Install Docker
- include_tasks: ../../tasks/docker.yaml

- name: "Copy Dkr Compose template"
  template:
    src: docker-compose.yaml.j2
    dest: "{{ project_path }}/docker-compose.yaml"
    force: yes

- name: Create Data folder
  file:
    state: directory
    path: "{{ project_path }}/data"

- name: Permission Data Folder
  command: "chmod -R 777 ./data"
  args:
    chdir: "{{ project_path }}"

- name: "Copy .env template"
  template:
    src: .env.j2
    dest: "{{ project_path }}/.env"
    force: yes

- name: Install SuiteCRM using Dkr Compose
  become: true
  command: docker compose up -d
  args:
    chdir: "{{ project_path }}"

- set_fact:
    url_ping: "http://{{ vm_ip }}:5080"

- name: Pause play until a URL is reachable from this host
  ignore_errors: true
  ansible.builtin.uri:
    url: "{{ url_ping }}"
    follow_redirects: none
    validate_certs: no
    method: GET
  register: _result
  until: _result.status >= 200
  retries: 30
  delay: 5

- include_tasks: ../../tasks/reboot.yaml
