---
- name: Docker
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # Wait until all unable to acquire the dpkg frontend lock process finished
    - include_tasks: ../../tasks/cloud-init.yaml

    # Playbook init (with decoded_metadata, project_path, app_secret, admin_email)
    - include_tasks: ../../tasks/playbook-init.yaml

    # Install Docker
    - include_tasks: ../../tasks/docker.yaml

    # - include_tasks: ../../tasks/reboot.yaml

    - name: Read Docker version
      become: true
      command: docker --version
      register: version_output

    - include_tasks: ../../tasks/expose-variable.yaml
      vars:
        text: |
          Docker instance details:

          Version: {{ version_output.stdout }}
