version: "3"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: "bitnami/zookeeper:latest"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - nifinet

  nifi:
    image: apache/nifi:latest
    ports:
      - 6980:8080
    networks:
      - nifinet
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey

networks:
  nifinet:
    driver: bridge
