version: "3.9"
services:
  nifi:
    image: apache/nifi:1.23.2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      # - 8080:8080
      - 8443:8443
    volumes:
      - ./data:/data
      - ./driver:/driver
      - ./extensions:/opt/nifi/nifi-current/extensions
