version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    container_name: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    restart: unless-stopped
    command: "start"
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./exports:/opt/keycloak/exports
    depends_on:
      - postgres
