# Install Docker
- include_tasks: ../../tasks/docker.yaml

- name: Root path
  set_fact:
    frappe_path: "{{ project_path }}/frappe_docker"

- name: Copy pwd.yml
  ansible.builtin.copy:
    src: pwd.yml
    dest: "{{ frappe_path }}/pwd.yml"
    force: yes

- name: Install ERPNext
  become: true
  command: "docker compose -f pwd.yml up -d"
  args:
    chdir: "{{ frappe_path }}"

- set_fact:
    url_ping: "http://{{ vm_ip }}"

- name: Pause play until a URL is reachable from this host
  ignore_errors: true
  ansible.builtin.uri:
    url: "{{ url_ping }}"
    follow_redirects: none
    validate_certs: no
    method: GET
  register: _result
  until: _result.status >= 200
  retries: 30
  delay: 5

# - include_tasks: ../../tasks/reboot.yaml
