- debug:
    var: email_var

- set_fact:
    email_regex: ^[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+$

- name: Ensure email variable is set
  assert:
    that:
      - email_var is defined and email_var != ''
    fail_msg: "Email variable is not set or is empty."
    quiet: yes

- name: Ensure email variable satisfies email regex
  assert:
    that:
      - email_var | regex_search(email_regex)
    fail_msg: "Email variable does not satisfy the Email address format."
    quiet: yes
