---
- name: Penpot Configuration
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - include_tasks: ../../tasks/variables.yaml

    - name: Extract Required Variables
      set_fact:
        configuration_type: "{{ decoded_metadata | json_query('configuration_type') }}"

    - include_tasks: configuration/ldap.yaml
      when: configuration_type == "ldap"

    - include_tasks: configuration/smtp.yaml
      when: configuration_type == "smtp"

    - include_tasks: configuration/authentik-sso.yaml
      when: configuration_type == "authentik_sso"
