---
- name: Test debug
  debug:
    msg: "{{ansible_distribution_version}}  {{ansible_distribution}}"

# tasks file for ansible-zimbra-single
- name: import centos.yml
  import_tasks: centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - zimbra_verion == "zimbra8"

- name: import centos-8.yml
  import_tasks: centos-8.yml
  when:
    - (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8") or (ansible_distribution == "Rocky" and ansible_distribution_major_version == "8")
    - zimbra_verion == "zimbra8"

- name: import ubuntu.yml
  import_tasks: ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"
    - zimbra_verion == "zimbra8"

- name: import ubuntu-2004.yml
  import_tasks: ubuntu-2004.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
    - zimbra_verion == "zimbra8"

- name: import zimbra9-centos.yml
  import_tasks: zimbra9-centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - zimbra_verion == "zimbra9"

- name: import zimbra9-centos-8.yml
  import_tasks: zimbra9-centos-8.yml
  when:
    - (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8") or (ansible_distribution == "Rocky" and ansible_distribution_major_version == "8")
    - zimbra_verion == "zimbra9"

- name: import zimbra9-ubuntu.yml
  import_tasks: zimbra9-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"
    - zimbra_verion == "zimbra9"

- name: import zimbra9-ubuntu-2004.yml
  import_tasks: zimbra9-ubuntu-2004.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
    - zimbra_verion == "zimbra9"
