---
- name: Joomla Configuration
  hosts: localhost
  become: false
  gather_facts: true
  vars:
    oidc_plugin_url: "https://prod-marketing-site.s3.amazonaws.com/plugins/joomla/miniorange-joomla-oauth-client-free-plugin.zip"

  tasks:
    - include_tasks: ../../tasks/variables.yaml

    - name: Extract Required Variables
      set_fact:
        configuration_type: "{{ decoded_metadata | json_query('configuration_type') }}"

    - include_tasks: configuration/keycloak-sso.yaml
      when: configuration_type == "keycloak_sso"
