- name: htaccess file htaccess
  stat:
    path: "{{ config_folder }}/.htaccess"
  register: htaccess_file_stat

- name: Write Site URL Config
  ansible.builtin.blockinfile:
    path: "{{ htaccess_file_stat.stat.path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HTACCES CONGIRURATION"
    block: |
      php_value upload_max_filesize {{ php_upload_max_filesize }}
      php_value post_max_size {{ php_post_max_size }}
      php_value max_execution_time {{ php_max_execution_time }}
      php_value max_input_time {{ php_max_input_time }}
  when: htaccess_file_stat.stat.exists
