---
- name: Jitsi Meet Configuration
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # Wait until all unable to acquire the dpkg frontend lock process finished
    - include_tasks: ../../tasks/cloud-init.yaml

    # Playbook init (with decoded_metadata, project_path)
    - include_tasks: ../../tasks/playbook-init.yaml

    - name: Extract Required Variables
      set_fact:
        configuration_type: "{{ decoded_metadata | json_query('configuration_type') }}"

    - name: Jitsi Facts
      set_fact:
        jitsi_path: "{{ project_path }}/docker-jitsi-meet-stable-8960-1"

    - include_tasks: configuration/ldap.yaml
      when: configuration_type == "ldap"
