- name: Check status file
  stat:
    path: /var/lib/cloud/instance/boot-finished
  register: status_file

- name: Wait for cloud-init logs
  wait_for:
    path: /var/log/cloud-init.log
    search_regex: "Cloud-init .* finished"
  register: logs_finished
  until: logs_finished is succeeded
  retries: 15
  delay: 10

- name: Check dpkg lock status
  shell: |
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
      echo "Waiting for other processes to release dpkg lock..."
      sleep 1
    done
  register: dpkg_lock_status
  changed_when: false
  retries: 10
  delay: 2

- name: Display lock status
  debug:
    msg: "All processes unable to acquire dpkg lock have finished."
  when: dpkg_lock_status.stdout == ""
