---
- name: Install Docker dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: Add Docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Docker | Install
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
    state: present
    update_cache: true

- name: Docker | Install Docker Module for Python
  pip:
    name: docker

- name: Docker | Add group user
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
