- name: Expose text variable
  ansible.builtin.debug:
    msg: "%%%{{ text }}%%%"
  when: text is defined

- name: Expose credentials variable
  ansible.builtin.debug:
    msg: "%$%{{ credentials|to_json }}%$%"
  when: credentials is defined
