- name: Mysql Password
  tags: [mysql]
  debug:
    var: mysql_root_password

- name: MariaDB | Install and dependencies
  tags: [mysql]
  apt:
    name:
      - python3-pip
      - mariadb-server
      - mariadb-client
      - mariadb-common
      - libmysqlclient-dev
    state: present

- name: MySQL | Pip Install Pymysql
  tags: [mysql]
  pip:
    name: pymysql
    state: present

- name: MySQL | start and enable mysql service
  tags: [mysql]
  service:
    name: mysql
    state: started
    enabled: yes

- name: Ensure MySQL root user has a password
  tags: [mysql]
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Remove anonymous user accounts
  tags: [mysql]
  mysql_user:
    name: ""
    host_all: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: absent

- name: Remove test database
  tags: [mysql]
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: absent
