- name: APT | Update & Upgrade
  become: true
  apt:
    upgrade: true
    update_cache: yes

- name: Root path
  set_fact:
    project_path: "/home/{{ ansible_user }}/projects/{{ platform_name }}"

- name: Create root path
  become: false
  file:
    state: directory
    path: "{{ project_path }}"
    recurse: yes

- name: Decode base64 platform_metadata variable
  set_fact:
    decoded_metadata: "{{ platform_metadata | b64decode }}"

- name: "Var | Debug decoded_metadata"
  debug:
    var: decoded_metadata

- name: "Var | Debug platform_name"
  debug:
    var: platform_name

- name: "Var | Debug random_secret"
  debug:
    var: random_secret

- name: "Var | Debug admin_email"
  debug:
    var: admin_email
