- name: Fact | Puppeteer folder
  set_fact:
    puppeteer_folder: "{{ project_path }}/.puppeteer"

- name: Create Puppeteer folder
  become: false
  file:
    state: directory
    path: "{{ puppeteer_folder }}"
    recurse: yes

- name: Install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - libgbm-dev

- include_tasks: nodejs.yaml

- name: Copy Package files
  become: false
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ puppeteer_folder }}/"
    force: true
  loop:
    - "../../puppeteer/package.json"
    - "../../puppeteer/pnpm-lock.yaml"
    - "../../puppeteer/tsconfig.json"

- name: PNPM | Install dependencies
  become: false
  command: "pnpm install"
  args:
    chdir: "{{ puppeteer_folder }}"
