- name: Fact | Puppeteer folder
  set_fact:
    puppeteer_folder: "{{ project_path }}/.puppeteer"

- name: Create Puppeteer folder
  become: false
  file:
    state: directory
    path: "{{ puppeteer_folder }}"
    recurse: yes

- name: Install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - libnss3
    - libxss1
    - libasound2
    - libatk-bridge2.0-0
    - libgtk-3-0
    - libgbm-dev

- include_tasks: nodejs.yaml

- name: Copy Package files
  become: false
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ puppeteer_folder }}/{{ item.name }}"
    force: true
  loop:
    - { file: "../../puppeteer/package.json", name: "package.json" }
    - { file: "../../puppeteer/pnpm-lock.yaml", name: "pnpm-lock.yaml" }
    - { file: "../../puppeteer/tsconfig.json", name: "tsconfig.json" }
    - { file: "../../puppeteer/src/utils.ts", name: "utils.ts" }

- name: PNPM | Install dependencies
  become: false
  command: "pnpm install"
  args:
    chdir: "{{ puppeteer_folder }}"
