- name: Fact | Puppeteer folder
  set_fact:
    puppeteer_folder: "{{ playbook_dir | dirname | dirname | dirname  }}/puppeteer"
  delegate_to: 127.0.0.1

- name: Install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - libnss3
    - libxss1
    - libasound2
    - libatk-bridge2.0-0
    - libgtk-3-0
    - libgbm-dev
  delegate_to: 127.0.0.1
  when: ansible_distribution == "Ubuntu"

- name: Check if Node.js is installed
  command: "node -v"
  register: node_version
  ignore_errors: true # Ignore errors if 'node' command is not found
  delegate_to: 127.0.0.1

- import_tasks: nodejs.yaml
  become: true
  when: ansible_distribution == "Ubuntu" and node_version.rc != 0
  delegate_to: 127.0.0.1

- name: NPM | Install PNPM, YARN, PM2
  become: true
  when: ansible_distribution == "Ubuntu"
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  loop:
    - pnpm
    - yarn
    - pm2
  delegate_to: 127.0.0.1

- name: PNPM | Install dependencies
  become: false
  command: "pnpm install"
  args:
    chdir: "{{ puppeteer_folder }}"
  delegate_to: 127.0.0.1
