version: "3.8"
services:
  postgres:
    image: postgres:${PG_VERSION:-15}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-db-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres-db-network

volumes:
  postgres-data:

networks:
  postgres-db-network:
    driver: bridge
