# Variable output (puppeteer_folder)
- include_tasks: "../../tasks/puppeteer-localhost.yaml"

- name: keycloak-client file
  set_fact:
    keycloak_client_file: "{{ puppeteer_folder }}/src/{{ random_secret }}-keycloak.ts"
    nextcloud_sso_file: "{{ puppeteer_folder }}/src/{{ random_secret }}-nextcloud.ts"

- name: "Copy keycloak-client.ts template"
  become: false
  template:
    src: "{{ scripts_dir }}/templates/puppeteer/keycloak-client.ts.j2"
    dest: "{{ keycloak_client_file }}"
    force: yes
  vars:
    keycloak_url: "{{ configuration['keycloak_url']  }}"
    keycloak_admin: "{{ configuration['keycloak_admin']  }}"
    keycloak_password: "{{ configuration['keycloak_password']  }}"

- name: "Run keycloak-client.ts"
  become: false
  command: "pnpm ts-node {{ keycloak_client_file }}"
  args:
    chdir: "{{ puppeteer_folder }}"
  register: client_key

- name: Keycloak client secret
  set_fact:
    client_secret: "{{ client_key.stdout | regex_search('%%%(.*?)%%%') | replace('%%%', '') }}"

- name: "Copy nextcloud-sso.ts template"
  become: false
  template:
    src: puppeteer/nextcloud-sso.ts.j2
    dest: "{{ nextcloud_sso_file }}"
    force: yes
  vars:
    instance_url: "{{ instance_url }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"

    oidc_endpoint: "{{ configuration['keycloak_url'] }}"
    oidc_client_id: "{{ keycloak_client_id }}"
    oidc_client_secret: "{{ client_secret }}"
    oidc_provider_name: "keycloak"

    authorize_url: "{{ oidc_endpoint }}/realms/master/protocol/openid-connect/auth"
    token_url: "{{ oidc_endpoint }}/realms/master/protocol/openid-connect/token"
    user_info_url: "{{ oidc_endpoint }}/realms/master/protocol/openid-connect/userinfo"
    scopes: "openid"
    button_style: "keycloak"

- name: "Run nextcloud-sso.ts"
  become: false
  command: "pnpm ts-node {{ nextcloud_sso_file }}"
  args:
    chdir: "{{ puppeteer_folder }}"

- name: "Remove {{ item }}"
  become: false
  command: "rm -rf {{ item }}"
  args:
    chdir: "{{ puppeteer_folder }}"
  loop:
    - "{{ keycloak_client_file }}"
    - "{{ nextcloud_sso_file }}"
