version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: unless-stopped
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    env_file:
      - .env

  moodle:
    image: docker.io/bitnami/moodle:4.2
    restart: unless-stopped
    ports:
      - '5080:8080'
      - '5443:8443'
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
