---
- name: Moodle Configuration
  hosts: localhost
  become: false
  gather_facts: true
  vars:
    oidc_plugin_name: "auth_oidc_moodle42_2023042400.zip"
    oidc_plugin_url: "https://moodle.org/plugins/download.php/29296/{{ oidc_plugin_name }}"

  tasks:
    - include_tasks: ../../tasks/variables.yaml

    - name: Extract Required Variables
      set_fact:
        configuration_type: "{{ decoded_metadata | json_query('configuration_type') }}"

    - include_tasks: configuration/keycloak-sso.yaml
      when: configuration_type == "keycloak_sso"
