# Install Docker
- include_tasks: ../../tasks/docker.yaml

- name: "Copy Dokr templates"
  template:
    src: "{{ item }}.j2"
    dest: "{{ project_path }}/{{ item }}"
    force: yes
  loop:
    - .env
    - docker-compose.yaml

- name: Install Authentik using Dkr Compose
  become: true
  command: docker compose up -d
  args:
    chdir: "{{ project_path }}"

- set_fact:
    url_ping: "http://{{ vm_ip }}:9980"

- name: Pause play until a URL is reachable from this host
  ignore_errors: true
  ansible.builtin.uri:
    url: "{{ url_ping }}"
    follow_redirects: none
    validate_certs: no
    method: GET
  register: _result
  until: _result.status >= 200
  retries: 30
  delay: 10

- include_tasks: ../../tasks/reboot.yaml
