version: "2.3"

services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - /var/gotify/data:/app/data
    ports:
      - 8080:80
