# Install Docker
- include_tasks: ../../tasks/docker.yaml

- name: Copy Dkr file
  ansible.builtin.copy:
    src: "docker-compose.yaml"
    dest: "{{ project_path }}/docker-compose.yaml"
    force: yes

- name: Create a directory /var/gotify
  ansible.builtin.file:
    path: /var/gotify
    state: directory
    mode: "0755"

- name: Download Gotify config example file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/gotify/server/master/config.example.yml
    dest: /var/gotify/config.yml
    mode: "0644"

- name: Replace admin pass
  ansible.builtin.replace:
    path: "/var/gotify/config.yml"
    regexp: "pass\\: admin"
    replace: "pass: {{ app_secret }}"

- name: Install Gotify using Dkr Compose
  become: true
  command: docker compose up -d
  args:
    chdir: "{{ project_path }}"

- set_fact:
    url_ping: "http://{{ vm_ip }}:8080"

- name: Pause play until a URL is reachable from this host
  ignore_errors: true
  ansible.builtin.uri:
    url: "{{ url_ping }}"
    follow_redirects: none
    validate_certs: no
    method: GET
  register: _result
  until: _result.status >= 200
  retries: 30
  delay: 5
