- name: Get Env WAZUH MANAGER
  become: false
  delegate_to: 127.0.0.1
  command: "python3 lib/getenv.py WAZUH_MANAGER"
  args:
    chdir: "{{ provisioner_dir }}"
  register: wazuh_manager_ip

- set_fact:
    wazuh_manager: "{{ decoded_metadata | json_query('wazuh_manager_ip') | default(wazuh_manager_ip.stdout, true) | trim }}"

- include_tasks: ../version.yaml

- name: "Wazuh Agent"
  when: wazuh_manager | ansible.utils.ipaddr
  block:
    - name: Import Wazuh GPG key
      become: true
      ansible.builtin.apt_key:
        url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
        state: present

    - name: Add Wazuh repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/{{ wazuh_major_version }}.x/apt/ stable main"
        state: present
        filename: wazuh

    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: Install wazuh-agent
      become: true
      ansible.builtin.apt:
        name: wazuh-agent
        state: present
        update_cache: yes # This is optional since we updated the cache just before
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}" # Define the environment variable for the task

    - name: Reload systemd daemon
      become: true
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable wazuh-agent service
      become: true
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start wazuh-agent service
      become: true
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started
