- name: Get Env WAZUH MANAGER
  become: false
  delegate_to: 127.0.0.1
  command: "python3 lib/getenv.py WAZUH_MANAGER"
  args:
    chdir: "{{ provisioner_dir }}"
  register: wazuh_manager_ip

- set_fact:
    wazuh_manager: "{{ decoded_metadata | json_query('wazuh_manager_ip') | default(wazuh_manager_ip.stdout, true) | trim }}"

- include_tasks: ../version.yaml

- name: "Wazuh Agent"
  when: wazuh_manager | ansible.utils.ipaddr
  block:
    - name: Download Wazuh GPG key and import it
      ansible.builtin.shell: |
        curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import
      args:
        executable: /bin/bash
      register: gpg_import_result
      changed_when: "'imported' in gpg_import_result.stdout or 'unchanged' in gpg_import_result.stdout"

    - name: Ensure correct permissions on the Wazuh GPG keyring
      ansible.builtin.file:
        path: /usr/share/keyrings/wazuh.gpg
        owner: root
        group: root
        mode: "0644"
      when: gpg_import_result.changed

    - name: Add Wazuh repo to the apt sources list
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/wazuh.list
        block: |
          deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/{{ wazuh_major_version }}.x/apt/ stable main
        state: present
        create: yes

    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: Install wazuh-agent
      become: true
      ansible.builtin.apt:
        name: wazuh-agent
        state: present
        update_cache: yes # This is optional since we updated the cache just before
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}" # Define the environment variable for the task

    - name: Reload systemd daemon
      become: true
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable wazuh-agent service
      become: true
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start wazuh-agent service
      become: true
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started

# Only for debug purpose
- name: Ending the 1st play now
  when: wazuh_manager | ansible.utils.ipaddr
  meta: end_play
